# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-10 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.IntegerField(null=True)),
                ('turn', models.IntegerField(null=True)),
                ('board', models.CharField(max_length=2000)),
            ],
        ),
    ]
