# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-12 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180410_2057'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='game',
            new_name='gamer',
        ),
    ]
