# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-12 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180412_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamer',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
