# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-12 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_gamer_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamer',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamer',
            name='turn',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
